### ISSUE TITLE
Use github action to publish static html page for the documentation

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#1]

**Comment by ndarmage** [comment]
The documentation produced by Sphinx is now available on github-pages after push on the branch master. This is a temporary solution, awaiting to deploy such documentation directly to github-pages by specific actions.

**Comment by ndarmage** [comment]
**NOTE** : There are two readme files now; the first is a short version of `docs/source/readme_full.rst` - it is recommended to find a different solution by extracting the short version from the full one without writing twice the contents in distinct files.

**Comment by panDanieleN** [comment]
Solved using github action defined in pages.yml (commit acb74320885fbf96aa0ab8c19a0c32cb17b1d79f)
