### ISSUE TITLE
Add the pressure info inside the __repr__ method.

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#106]
Add the pressure value among the print returned by the `__repr__`

**Comment by lelaus** [comment]
In addition to insert the pressure value among the values printed into the stdout, the key management instruction has been removed. This instruction was needed when the keys of the `__properties` dict where made by two components, but now the keys are only made by the name of the properties, thus making the key management useless.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update tests.

Documentation update handled in #47
