### ISSUE TITLE
Liquid metal density shall depend on pressure as well

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#11]
In LMFR hydrostatic pressure of the coolant is not negligible. This has an impact on coolant density which is crucial for criticality
calculations. Therefore, lbh15 shall provide correction on density as function of the pressure. 

The handbook provides the correlation to adopt in Eq. 2.78

**Comment by panDanieleN** [comment]
Liquid metal objects take also pressure as parameter at initialization. Only density actually uses it.

Branch: pressureDep
commit: 65a43deeb8d94ff14d2ca962f51c236ef01497cd

**Comment by ndarmage** [comment]
A substance in liquid phase needs two thermodynamic variables to define its state. Temperature and pressure are the default choice following the reference handbook. The basic equation of state yielding the liquid lead density is valid only at atmospheric pressure. Eq. 2.78 provides a correction based on a 1st order truncated Taylor expansion. So atm pressure should be the default value for pressure when calling the state equation, while temperature should not have any default value.

**Comment by panDanieleN** [comment]
Merged into master
