### ISSUE TITLE
Need for a test covering all temperatures

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#113]
To assure the robustness of the initialization of the liquid metal objects from properties other than the temperature, there is the need to apply the test_lbh15_fromX.py test to the entire admissible temperature range. So far, only two temperature values are tested, a low one (395 °C) and a high one (1500 °C), for all the metals. More detailed tests should be implemented, one for each liquid metal, covering the corresponding temperature range between the melting and the boiling values.

**Comment by lelaus** [comment]
3 new tests to add to the CI/CD procedure.

**Comment by panDanieleN** [comment]
Merged into master.

Added tests as described in the issue, removed obsolete `test_lbh15_fromX.py` test.

No need to update documentation.
