### ISSUE TITLE
Ensure element-wise function evaluation

### ISSUE THREAD

**Issue by ndarmage** [newcleo-dev-team/lbh15#12]
Make sure that any function is implemented allowing element-wise operations, so that correlations can be called on simple scalars and arrays at the same time. The use of np.array is suggested.

**Comment by panDanieleN** [comment]
Checked  that all properties' correlation can handle numpy array. Removed usage of np.power (in rho correlation) since useless.

Branch: master
commit: c437d4ad35310f2972ea4710884d16578929b3a8

**Comment by panDanieleN** [comment]
Modify the implementation of correlations which are expressed as polynomials for two reasons:
- avoid errors in the case in which the functions are evaulated with numpy.arrays with dtype int
- optimize performances

Therefore, expressions like `T**2` shall be replaced with `T*T`

**Comment by panDanieleN** [comment]
Done as in previous comment.

Branch: rep_exp_with_mult
Commit: 337f140f1e7f4e961efe03384548ce95c062b5e2

**Comment by panDanieleN** [comment]
Merged into master.
