### ISSUE TITLE
Review for v2.0.0 release

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#120]
Modifications and/or additions to apply:
1. use tex corporate class for pdf generation; #24 
2. separate "contacts" and "acknowledgments" sections;
3. insert "how to cite" sub-section into "contacts" section;
4. correct typos when referencing tables and figures;
5. terminate all captions with ".";
6. make sections starting from "Contacts" not numbered;
7. show links in full text format (short links) or as footnotes (long links) for making them readable even when the pdf is printed; 
8. in the "installation" section, add a note about how to upgrade the package;
9. in the code, change "correlations_available" name into "available_correlations", and check for other similar issues;
10. to address #123, #124 and #126 issues

**Comment by lelaus** [comment]
In 3f78fba, the tex corporate template has been added for pdf generation. Some issues yet to solve:
1. authors alignment not handled properly; when newline, something weird affects reviewers and approvers columns;
2. header of toc page; basically, it appears only if `\fancypagestyle{plain}{}` added to latex template; check whether this issue can be solved directly by modifying the corporate class;
3. the background of the header on pages where long tables (`:class:longtable`) are splitted across multiple pages looks strange;
4. `chapter` not natively present in the corporate class; trying to find an alternative;
5. to give the user the possibility to choose between adopting either the corporate or the standard template classes.

**Comment by lelaus** [comment]
In d1646ea, the `:math:` role has been converted into `.. math::` directive for deleting `\displaystyle` feature only in `learn_more.rst`. In `lead.rst`, `bismuth.rst` and `lbe.rst` this change has not been applied since, coupled with the "rtd_theme", the formulae would appear in the middle of the page, reducing the readability.

**Comment by panDanieleN** [comment]
Merged into master. 

Updated documentation as described inside the thread.
No need to update tests.

**Comment by lelaus** [comment]
Some additional minor corrections to documentation and comments are needed.

**Comment by panDanieleN** [comment]
Minor corrections handled in #131.
