### ISSUE TITLE
Regularization of \displaystyle equations and \Big modifiers

### ISSUE THREAD

**Issue by papantel** [newcleo-dev-team/lbh15#126]
Some `\displaystyle` instructions and `\Big` modifiers are used in RST files (on master: `lead.rst`, `bismuth.rst`, `lbe.rst`). It would be prettier and more automatic if:
- `:math:` role containing `\displaystyle` instructions were replaced by `.. math::` directive;
- `\Big` modifiers in `:math:` roles or `.. math::` directives were replaced by `\left` and `\right` modifiers.

**Comment by panDanieleN** [comment]
Addressed in #120
