### ISSUE TITLE
Use pyproject.toml to define a dev installation

### ISSUE THREAD

**Issue by papantel** [newcleo-dev-team/lbh15#128]
The `setup.py` and `pyproject.toml` files have the same purpose, and `setup.py` is the old-fashioned way to define install options.
It is possible to delete `setup.py` after testing that the `pyproject.toml` is equivalent.

Moreover, `pyproject.toml` allows to create a optional installation of the lbh15 package which can provide auto-installation of developper-used packages. To do so, the `pyproject.toml` can contain the following lines:
```toml
[project.optional-dependencies]
dev = [
    "sphinx>=7.2.6",
    "sphinx-rtd-theme>=2.0.0",
    "sphinxcontrib-bibtex>=2.6.1",
    "myst-parser>=2.0.0",
    "simple-pid>=2.0.0",
    "matplotlib>=3.8.2",
    "black[d]>=23.11.0",
]
```
This section allows the following command:
```bash
pip install .[dev]
```

Note: this list was established following an analysis of the code version on 120_review_pre_v2 branch.

**Comment by panDanieleN** [comment]
Closed since not necessary at the moment.
