### ISSUE TITLE
Remove typecheck for performance reasons

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#129]
Remove the typecheck decorator since it determines a great overhead. Anyway, it should not be removed completely, but it should be placed in a dedicated branch to make it available in the future if needed.

**Comment by panDanieleN** [comment]
In addtion, define "How to cite" section inside main `README.rst` file of the project.

**Comment by panDanieleN** [comment]
Merged into master. 

Updated `README.rst`.
No need to update tests.
