### ISSUE TITLE
Reset of liquid-metal objects

### ISSUE THREAD

**Issue by ndarmage** [newcleo-dev-team/lbh15#13]
Currently, a liquid metal object is instantiated provided a given thermo-dynamic state at input. When the instance is needed at a different thermo-dynamic state, a new instance must be created. This may imply an inefficient use of memory, especially when the same liquid metal object is wanted.

The possibility of instance reset (at different thermo-dynamic state) shall be considered for future code versions.

**Comment by panDanieleN** [comment]
Added setter of pressure and temperature. Example of usage:
```python
from lbh15 import 
```

**Comment by panDanieleN** [comment]
Solved as previous comment.

Branch: master
commit: 7aced594a05689703ca49cfdd630858e43246b99
