### ISSUE TITLE
SI Units

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#135]
For the time being, some correlations use quantities that are not expressed in SI Units.
In detail the following methods (and/or docstring therein) must be modified to use quantities that are expressed in SI Units:

- [x] `OxygenPartialPressureInterface.initialization_helper()` from _atm_ to _Pa_ (`bismuth_thermochemical.py` module);
- [x] `OxygenPartialPressureInterface.units()` from _atm_ to _Pa_ (`bismuth_thermochemical.py` module);
- [x] `OxygenPartialPressureFitzner1980.correlation()` from _atm_ to _Pa_ (`bismuth_thermochemical.py` module);
- [x] `OxygenPartialPressureIsecke1979.correlation()` from _atm_ to _Pa_ (`bismuth_thermochemical.py` module);
- [x] `OxygenPartialPressureHahn1979.correlation()` from _atm_ to _Pa_ (`bismuth_thermochemical.py` module);
- [x] `OxygenPartialPressureHeshmatpour1981.correlation()` from _atm_ to _Pa_ (`bismuth_thermochemical.py` module);
- [x] `OxygenDiffusivityInterface.units()` from _cm_ to _m_ (`diffusivity_in_bismuth.py` module);
- [x] `OxygenDiffusivityFitzner1980.correlation()` from _cm_ to _m_ (`diffusivity_in_bismuth.py` module);
- [x] `OxygenDiffusivityHeshmatpour1981.correlation()` from _cm_ to _m_ (`diffusivity_in_bismuth.py` module);
- [x] `OxygenDiffusivityInterface.units()` from _cm_ to _m_ (`diffusivity_in_lbe.py` module);
- [x] `OxygenDiffusivityGromov1996.correlation()` from _cm_ to _m_ (`diffusivity_in_lbe.py` module);
- [x] `OxygenDiffusivityGanesan2006b.correlation()` from _cm_ to _m_ (`diffusivity_in_lbe.py` module);
- [x] `IronDiffusivity.correlation()` from _cm_ to _m_ (`diffusivity_in_lbe.py` module);
- [x] `IronDiffusivity.units()` from _cm_ to _m_ (`diffusivity_in_lbe.py` module);
- [x] `OxygenPartialPressure.initialization_helper()` from _atm_ to _Pa_ (`lbe_thermochemical.py` module);
- [x] `OxygenPartialPressure.correlation()` from _atm_ to _Pa_ (`lbe_thermochemical.py` module);
- [x] `OxygenPartialPressure.units()` from _atm_ to _Pa_ (`lbe_thermochemical.py` module);
- [x] `OxygenDiffusivityInterface.units()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `OxygenDiffusivityArcella1968.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `OxygenDiffusivityHomna1971.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `OxygenDiffusivitySwzarc1972.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `OxygenDiffusivityOtsuka1975.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `OxygenDiffusivityCharle1976.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `OxygenDiffusivityGromov1996.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `OxygenDiffusivityGanesan2006b.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `IronDiffusivity.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `IronDiffusivity.units()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `CobaltDiffusivity.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `CobaltDiffusivity.units()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `SeleniumDiffusivity.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `SeleniumDiffusivity.units()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `IndiumDiffusivity.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `IndiumDiffusivity.units()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `TelluriumDiffusivity.correlation()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `TelluriumDiffusivity.units()` from _cm_ to _m_ (`diffusivity_in_lead.py` module);
- [x] `OxygenPartialPressureInterface.initialization_helper()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureInterface.units()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureOtsuka1979.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureOtsuka1981.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureGanesan2006.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureAlcock1964.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureSzwarc1972.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureCharle1976.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureIsecke1977.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureTaskinen1979.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `OxygenPartialPressureFisher1966.correlation()` from _atm_ to _Pa_ (`lead_thermochemical.py` module);
- [x] `_commons.py` module: `LEAD_MOLAR_MASS`, `BISMUTH_MOLAR_MASS`, `LBE_MOLAR_MASS` and `OXYGEN_MOLAR_MASS` from _g_ to _kg_;
- [x] `Bismuth` class docstring;
- [x] `LBE` class docstring;
- [x] `Lead` class docstring;

**Comment by lelaus** [comment]
Also reference values for tests must be updated accordingly.

**Comment by panDanieleN** [comment]
Merged into master.

Modified doc and tests as described above.
