### ISSUE TITLE
Need for a method for retrieving the correlations that are available for a specific property

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#136]
So far, the `available_correlations()` method provides information about the correlations that are available for all the properties. It could be useful to have also a method providing the same information for a specific property passed as argument.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.

**Comment by lelaus** [comment]
So far, the new method `available_corrs_for_property()` has been added. Merging this method with the `available_correlations()` one should improve the readability and should avoid any misuse and any misleading.

**Comment by panDanieleN** [comment]
Merged into master.

Updated doc to show how to retrieve available correlations only for user specified properties.

No need to update tests.
