### ISSUE TITLE
Perform code static analysis using pylint

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#14]
Static analysis is a method of program debugging that is done examining the code without executing it. The process provides undertanding of the code structure and can help ensure that the code adheres to industry standards.

pylint is the common tool used for static analysis of python programs.

**Comment by panDanieleN** [comment]
Updated code with pylint suggestions. Main changes:
- avoided use of abc.abstractproperty since deprecated. Adopted property + abc.abstractmethod
- use of f-strings where possible
- use of chained comparisons
- avoided use of useless __init__ function in properties objects
- removed useless variables
- updated documentation (definition of custom properties).

Naming convention warnings and minor code refactory left after modification.

Branch: statAnalysis
commit: 503072dc7d499115298af3d7b8b16d662d2c4ad5

Results of pylint:
- master branch score: 7.63/10
- statAnalysis branch score: 9.12/10

Number of code lines:
- master branch: 7183
- statAnalysis branch: 7080

**Comment by ndarmage** [comment]
Use of pylint can be requested as mandatory before any merge to master.

**Comment by panDanieleN** [comment]
merged into master
