### ISSUE TITLE
JOSS Submission Review (Reviewer 1): Software Paper

### ISSUE THREAD

**Issue by damar-wicaksono** [newcleo-dev-team/lbh15#145]
This issue is related to the [JOSS submission review](https://github.com/openjournals/joss-reviews/issues/6383).

Please find below some questions, remarks, and suggestions regarding the draft paper. Please feel free to let me know if you need clarification. Thanks!

**Summary**

- Line 14 "_...defined by its thermo-dynamic state,..._": I think it's more common to write "thermodynamic" instead of "thermo-dynamic".
- Lines 15-16 "_In addition, the value of several other properties can be used at liquid metal object’s instantiation,..._": This is not clear. Which other properties? Furthermore, I think (because I follow the tutorials) it means that the value of these properties can be used _instead_ of the temperature and pressure to instantiate the object (with the given injectivity condition); if so, this must be stated clearly here.

**Statement of Need**:

- Lines 28-29 "_In this context, standard libraries providing the physical correlations for thermal-hydraulic computer tools are needed._": It is not clear from this supposedly prominent sentence what "physical correlations" actually refers to (only in connection with the summary it is clear; by the way, I think they should be correlations of physical properties). Furthermore, "Standard libraries of physical correlations for thermal-hydraulic computational tools" are very broad and I think the closing of a statement of need should be a bit more focused.
- Lines 25-26, "_...in both industry and research environment,..._": Perhaps "industrial" instead of "industry" would be more apt?

**Implementation**:

- Line 31: The package `iapws` cited by the paper is archived at Zenodo with its own [DOI:10.5281/zenodo.4744318](https://zenodo.org/records/4744318). Perhaps this should appear in the list of references instead of a footnote.
- Line 34 "_The efficiency and the effectiveness are assured by the Object-Oriented ... approaches,..._": It may be more common to say "object-oriented design" instead of "object-oriented approach".

**Use**:

- Line 46: "thermodynamic" instead of "thermo-dynamic".
- Line 48 "_In addition, the former approach allows to manage the properties correlations in a simpler way..._": I think the verb "allows + to" is transitive, it needs an object, perhaps "the former approach allows users/one to manage...".
- Line 48 "_...by acting either on a single or on all liquid metal instances at the same time._": I'm not sure I understand the part "on all liquid metal instances at the same time" written here; If I instantiate _a_ liquid metal object to access its related properties, how can I act on all instances? Perhaps I misunderstood it.
- Line 51 "_...where it may be too much to know the values of all the properties..._": In which sense it is "too much" to know here? Is it in the sense of "knowing the values of all the properties are _unnecessary_"? Or?

**Implemented Properties**:

- These two subdivisions are not structured parallely, either use parentheses or "..., including...".
- I see no reason to capitalize the term "Oxygen".

**Implementation History**:

- Line 66, "_It improves the performance and the readability._": The readability of what? The documentation or the codebase as a whole?
- Line 67, "_... improving performance and usability (..._": In what way using vectorization and Horner's scheme improve usability of the package?
- Line 68, "_It includes a tutorial focusing on a volume of lead that is subjected to time-varying thermal loads..._": The sentence that came before focused on improved implementations, but this sentence focused on the documentation. It should be stated explicitly instead of using the pronoun "it".
- Lines 71-72, "_Great attention is paid to the code quality and readability_": This is somehow a repetition and extension of the second sentence of the paragraph. Perhaps combine them into a single sentence?
- Maybe add a footnote for the repository of `pycodestyle` and `pylint`?
- Lines 72-74, "_In addition, the automatic static analysis of the code has been performed by applying the pylint tool throughout the entire development, achieving a score higher than 9 out of 10._": Is stating the score really necessary here? While it is a very high score, it would be difficult to judge this number without really understanding what is being analyzed by `pylint`? Would it be enough to state that you ensure the quality of the code using tools like `pycodestyle` for styling and `pylint` for linting (and static code analysis)?

**Documentation**:

- Line 82, "_An advanced use of the package needs skills in Python software development_.": This is a very vague statement, what kind of skills in Python software development, specifically? Perhaps more importantly, if such a sentence is necessary, what is considered an "advanced use" of the package?
- Line 83, "_The documentation is completed with examples..._": Is the documentation complete? Or it will be kept getting updated along with new versions of the package? Perhaps "also includes various examples" would suffice?
- Line 83, "_...for the users, starting from basic use up to short tutorials for more advanced applications._":
  - "users" instead of "the users"
  - "starting from...": "starting" is not necessary
  - the term adopted in the documentation is "Basic Usage" instead of "Basic Use".
  - Similarly is it "advanced applications" or "advanced usage"?

**Comment by lelaus** [comment]
Dear @damar-wicaksono ,

we have tried to apply all your comments, remarks and suggestions. Please, find below our specific actions for each of your points.

In case of any misunderstanding and/or further comments and/or doubt, please do not hesitate to write us.

**Summary**
. Line 14: OK

. Lines 15-16:
	The authors agree with the reviewer's comment. Sentence changed into:
		_As alternative, the physical properties can be used at liquid metal object's instantiation, ..._
	See issue #141

**Statement of Need**
. Lines 28-29:
	changed _physical correlations_ into _correlations of physical properties_
	the "computational tools" have been specified by adding _, such as CFD, system and sub-channel codes concerning heavy liquid metals._

. Lines 25-26: OK

**Implementation**
. Line 31:
	Good point! Thanks!

. Line 34: OK

**Use**
. Line 46: OK

. Line 48: OK

. Line 48:
	The authors agree with the reviewer that the sentence is not clear.
	The sentence has been rewritten when managing issue #141 into:
		_In addition, this approach allows to select the default correlations of the properties by means of the available class methods._

. Line 51:
	The authors agree with the reviewer that the sentence is not clear.
	The second part of the sentence has been rewritten when managing issue #141 into:
		_... since it offers faster instantiation and evaluation of the correlation functions._

**Implemented Properties**
. These two subdivisions are not structured in parallel:
	The authors agree with the reviewer.
	The ":" has been inserted into both the subdivisions when managing issue #141, in order to make them parallel;

. I see no reason to capitalize the term "Oxygen".
	OK

**Implementation History**
. Line 66:
	_It improves the performance and readability._
	has been substituted with _It improves the overall understanding._

. Line 67:
	The point of view of the authors is:
	. The **vectorization** should improve the **usability** since the correlation functions may be called either by passing a single input (thus retrieving a single result) or by passing an array of inputs (thus retrieving an array of results at the same time). Without vectorization, the user should call the correlation functions multiple times, once for each element of the input array.
	. The **Horner scheme** is an efficient way of writing polynomials according to the provided reference: in this sense, coding polynomials according to this scheme improves the **performance** of the code.

. Line 68:
	"It" has been substituted with _The documentation of the current version_.

. Lines 71-72:
	The authors agree with the reviewer: "readability" has been removed since it would be a repetition, and the code quality sentences are made more concise and are moved upperwards.

. pycodestyle and pylint: OK

. Lines 72-74: OK

**Documentation**
. Line 82:
	The authors agree with the reviewer, thus the sentence has been removed.

. Line 83:
	"is completed with" has been substituted with "contains" when handling issue #141.
	The authors think that the modification complies also with what stated by the reviewer.

. Line 83:
	. "users" instead of "the users":
		already applied when handling issue #141
	. "starting from...":
		already applied when handling issue #141
	. here "_basic use_" and "_advanced applications_" are considered as general expressions, thus not needing a strict reference to the chapter naming adopted in the doc.

**Comment by damar-wicaksono** [comment]
Hello @lelaus,

I have read the updated draft manuscript and can confirmed the changes you made; along with the suggestions from the other reviewer, I think it is now a better read.

Thank you very much for taking the time going through my comments, addressing them, and providing explanations to some of my questions!

A couple other very minor suggestions:

- Line 32: Maybe add a space between `iapws` and "(Romera, 2021)"?
- As suggested by the editorialbot, it appears your own publication at NURETH has its [DOI:10.13182/nureth20-40554](https://doi.org/10.13182/nureth20-40554). Maybe consider adding the DOI to the manuscript?

Beyond these additional minor suggestions, I have no further comments regarding the manuscript. Feel free to close this issue afterwards (if changes are made). Thank you!

**Comment by damar-wicaksono** [comment]
And perhaps also this [DOI:10.1787/42dcd531-en](https://doi.org/10.1787/42dcd531-en) for the handbook (but please verify). Thanks!

**Comment by lelaus** [comment]
Yes, thanks @damar-wicaksono for noting this. I verified it is ok. About the other references I did not find any DOI.

**Comment by damar-wicaksono** [comment]
@lelaus, thanks! Everything looks good!
