### ISSUE TITLE
Clarify the statement of need

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#148]
To specify exactly who should use this software and why they should use it in README and in the documentation introduction.
To stress these aspects also in the introduction of the tutorial.

**Comment by lelaus** [comment]
This issue is also intended to solve the comments in the _**Introduction**_ section of issue #147.

**Comment by panDanieleN** [comment]
Merged into master. 

No need to update tests.

Modified doc as described in the issue.

**Comment by lelaus** [comment]
In README, the link to the "How to Contribute" section does not work. It has to be corrected by adding the ".rst" at the end.

**Comment by lelaus** [comment]
The "reopening" comment was not about this issue.
