### ISSUE TITLE
Add contributing document

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#150]
To include a contributing document describing how third parties can contribute to the software, report issues/problems with the software and seek support.
A code of conduct document should also be included at the same time.

**Comment by lelaus** [comment]
In the contributing file `CONTRIBUTIONS.rst` that has been added in commit [e8a139e](https://github.com/newcleo-dev-team/lbh15/commit/e8a139e6ef59d38336c6760108506f62b004b07d), the reader should be informed that the `unittest` framework must be used for testing the package.
This request comes from the "_Community Guidelines_" section of issue #147.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update tests.

Modified doc as described  by the issue.

**Comment by lelaus** [comment]
In README, the link to the "How to Contribute" section does not work. It has to be corrected by adding the ".rst" at the end.

**Comment by panDanieleN** [comment]
Merged into master.

Updated "Contacts" section of doc.
