### ISSUE TITLE
print() method not working

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#152]
This issue is relating to the first task of issue #144.

The method `print()` applied to a `LiquidMetalInterface` instance does not work. An error is always returned.
The reason is related to the customized implementation of the `__str__()` dunder method, and in particular to the following instruction:

`info = getattr(self, prop_name+"_info")(print_info=False, n_tab=1)`

Actually, `prop_name+"_info"` represents a lambda function, and no further arguments could be passed it.

A possible solution could be substituting the lambda function by a dedicated inner function within the `__add_property()` method. Other solutions could be investigated.

**Comment by panDanieleN** [comment]
Added arguments (with default value) to lambda function defined inside `__add_property`.

**Comment by lelaus** [comment]
Merged into master.

No need to update doc and test.
