### ISSUE TITLE
Checking separator when calling `set_custom_properties_path()` method

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#153]
This issue is relating to the last task of issue #144.

The `set_custom_properties_path()` method loads properties from the module whose path is passed as argument.
Currently, no check is made about the separator used in the passed path, so no catching any issue in case the used separator is not in accordance with the OS.
The check is needed to make the `set_custom_properties_path()` method more robust.

This issue is also related to issue #121, which is about the package to use for handling the separator-related aspects.

**Comment by panDanieleN** [comment]
The error described in #144 concerning `set_custom_properties_path` method seems to be only Windows related. Indeed, trying to replicate the same in Linux, the method works correctly:
```
>>> from lbh15 import Lead
>>> import os
>>> path = os.getcwd()+'\\tests\\custom_properties\\lead_properties.py'
>>> Lead.set_custom_properties_path(path)
sys:1: UserWarning: '/home/daniele.panico/sw_develop/mat_develop/lbh15\tests\custom_properties\lead_properties.py' provided file not found!
Please check the file path and try again!
No custom property added.
```
In other words, it returns a warning saying that the file does not exist and the module is not added. I think this behaviour is ok: the file does not exists if the separator is wrong.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update doc and tests.
