### ISSUE TITLE
Unnecessary use of `pprint`

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#154]
This issue is related to the second task of #144.

In the last bullet of "Basic Usage" section in the doc, `pprint` is adopted for providing summary info about a liquid metal instance. Actually, this method returns the same info as the `__repr__()` dunder method, thus resulting useless.

It seems preferable to remove `pprint`, and to substitute it by relying on the dunder `__repr__()` method.

**Comment by panDanieleN** [comment]
Merged into master.

Updated doc as described. 
No need to update tests.
