### ISSUE TITLE
Including all the dependencies for doc building and testing into toml and `setup.py`

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#155]
This issue is related to the second task of issue #147.

Actually, the dependencies required for building the doc and for performing tests are not included neither in the `pyproject.toml` file or in the `setup.py` file.
Adding them would improve the usability of the package.

**Comment by panDanieleN** [comment]
Added all the dependencies in `setup.py` and `pyproject.toml`.

**Comment by lelaus** [comment]
Merged into master.

No need to update the documentation and the tests.
