### ISSUE TITLE
Refactor _Advanced Usage_ section in the doc and correct errors therein

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#156]
This issue is related to the tasks of _Advanced Usage_ section in #147.

- [x] put the paragraph related to the `available_correlations()` example outside the bulleted list;
- [x] transform the two bullets into two subsections;
- [x] typo: from "_Let_" to "_Let's_"
- [x] pass separator in different OS (already treated in #153)
- [x] focus on listing only the relevant correlations, that is the ones available for `rho`
- [x] modify `Lead.correlations_available()` into `Lead.available_correlations()`
- [x] "_If the density correlation is not specified for a new object instantiation, the last one in the list will be selected as default:_": currently, the example below shows only what happens by using the `Lead.set_correlation_to_use()`; an example should be added showing the default behavior as noted here if the function `Lead.set_correlation_to_use()` is not used
- [x] modify the path `<execution_dir>/custom_property` into `<execution_dir>/custom_properties`.

**Comment by lelaus** [comment]
Task n.6 treated in #144.

**Comment by lelaus** [comment]
Task n. 1 handled in 1e77498.

**Comment by lelaus** [comment]
Task n.2 handled in 31c3cca.

**Comment by lelaus** [comment]
Task n.5 handled in 7454d24.

**Comment by lelaus** [comment]
Task n.8 handled in c133269.

**Comment by lelaus** [comment]
Task n.7 handled in 341a185.

**Comment by panDanieleN** [comment]
Merged into master.

Updated doc as described.
No need to update tests.
