### ISSUE TITLE
Checking the way the correlations provided with different validity ranges have been selected 

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#157]
This issue is related to the first task of the "_Ranges of Validity_" section in issue #147.

The reference handbook provides multiple validity ranges for some correlations. This aspect has been discussed together with the authors of the handbook. Together with them, it has been decided to adopt in _lbh15_ the lowest range. After having analysed the old issue(s) dealing with this aspect, the corresponding information should be detailed in the "_Ranges of Validity_" section of the doc.

**Comment by panDanieleN** [comment]
Communication with authors of the handbook are not related to this section of the doc. As explained in #44 they are related to the choice of some default correlations to adopt in `lbh15`. Going to share with @lelaus the summary of that communications.

Therefore, I just rephrased the section and followed the suggestions given in #147.

**Comment by lelaus** [comment]
Documentation modified as described by commits.

No need to update tests.
