### ISSUE TITLE
Unnecessary page in the html doc

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#158]
This issue is related to the first task of the "_API Guide_" section in the issue #147.

In the html doc, the page at link https://newcleo-dev-team.github.io/lbh15/source/lbh15.html is unnecessary since it is equal to the page at link https://newcleo-dev-team.github.io/lbh15/source/documentation.html. The former should be removed.

**Comment by panDanieleN** [comment]
Merged into master.

Updated doc as described.
No need to update tests.
