### ISSUE TITLE
Add monospace expression of all liquid metal properties

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#159]
This issue is related to the second task of the "_lead Module, bismuth Module, and lbe Module:_" in the issue #147.

The listed thermo-physical and thermo-chemical properties in the Lead, Bismuth and LBE modules' pages should be additionally written in monospace as they are directly related to properties of an instance.

**Comment by panDanieleN** [comment]
Merged into master.

Updated doc as described.
No need to update tests.
