### ISSUE TITLE
Increase abstraction level of `OxygenDiffusivityInterface` and `IronSolubility` classes

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#160]
This issue is related to the last task of the "_lead Module, bismuth Module, and lbe Module:_" section of issue #147.

Classes `OxygenDiffusivityInterface` and `IronSolubility` are implemented for Lead, Bismuth and LBE liquid metals, thus repeating the same codes. It should be better to insert an additional abstraction layer, by creating a `_common_interfaces.py` module where a class implementing the methods `name()`, `units()` and `long_name()` is defined.

The same should be done for any other ...`Interface` class experiencing the same behavior, in addition to the `OxygenDiffusivityInterface` and `IronSolubility` classes.

**Comment by panDanieleN** [comment]
Defined `tph_common_interface.py` and `tch_common_interface.py` modules for thermophysical and thermochemical property interfaces respectively.

The properties that actually uses `PropertyInterface` after the refactoring follows:

- `lbe_thermochemical_properties.lbe_thermochemical.LeadChemicalActivity`
- `lbe_thermochemical_properties.lbe_thermochemical.BismuthChemicalActivity`
- `lead_thermochemical_properties.diffusivity_in_lead.CobaltDiffusivity`
- `lead_thermochemical_properties.diffusivity_in_lead.SeleniumDiffusivity`
- `lead_thermochemical_properties.diffusivity_in_lead.IndiumDiffusivity`
- `lead_thermochemical_properties.diffusivity_in_lead.TelluriumDiffusivity`
- `lead_thermochemical_properties.lead_oxygen_limits.LowerLimitSilicon`
- `lead_thermochemical_properties.solubility_in_lead.SiliconSolubility`

Such properties do correspond with the ones listed in [tables](https://newcleo-dev-team.github.io/lbh15/source/readme_full.html) available only for one metal.

**Comment by panDanieleN** [comment]
Added `.rst` files for adding new modules inside the doc.

**Comment by panDanieleN** [comment]
Modified `properties_bounds.json` for executing `test_lbh15_bounds.py` since there was a bug in the `description` attribute of some thermochemical properties (see commit daebde0f5055557c1ec08e4888fa35bda671f414)

**Comment by panDanieleN** [comment]
`pylint` score of `properties` sub-package increased  to 9.99 (disabling `invalid-name`) compared to 9.91 of branch master.

**Comment by lelaus** [comment]
Merged into master.

Doc modified as per the insertion of two new modules (`tph_common_interface.py` and `tch_common_interface.py`).

Reference data file (`properties_bounds.json`) for tests modified as per correction of some typos in the `description` methods.
