### ISSUE TITLE
Add JOSS tag to the entry page of the project

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#181]
Insert in the README file the following snippet:

`reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.06383/status.svg
   :target: https://doi.org/10.21105/joss.06383`

**Comment by panDanieleN** [comment]
Added joss tag as described above. 
In addition, the "how to cite" section has been updated (in docs/source/contacts.rst)

**Comment by lelaus** [comment]
Merged into master.
No need to update tests.
Doc modified as described above.
