### ISSUE TITLE
Implementation of bismuth-related contamination properties

### ISSUE THREAD

**Issue by prisma34** [newcleo-dev-team/lbh15#185]
Add the correlations related to contaminating metallic compounds in pure bismuth, according to the sub-package defined in issue #183.
The correlations are: 

- [x] Polonium activity coefficient by Joy, 1963.

- [x] Iodine vapour pressure by Cubicciotti, 1959.

**Comment by lelaus** [comment]
The required properties have been implemented.

No modification yet applied to doc (issue #197).
No modification yet applied to test (issue #190).
