### ISSUE TITLE
Implementation of tests related to the contamination properties

### ISSUE THREAD

**Issue by prisma34** [newcleo-dev-team/lbh15#188]
Implement tests for initialization and boundary values verification in the `tests` package. Also reference data are to be added in file `properties_bounds.json`.

- [x] Tests for contamination properties in pure lead.

- [x] Tests for contamination properties in pure bismuth.

- [x] Tests for contamination properties in LBE.

This issue is related to what implemented for managing issue #183.

**Comment by lelaus** [comment]
Following the update of the `numpy` library, in 4b8d7d8 a few reference values that are used for test purposes have been changed.

**Comment by lelaus** [comment]
The tests related to the contaminant properties implemented for lead, bismuth and LBE have been added to _lbh15_.

No need to change the doc.
