### ISSUE TITLE
Implementation of LBE contamination's tests 

### ISSUE THREAD

**Issue by prisma34** [newcleo-dev-team/lbh15#191]
Implement tests for initialization and boundary values verification for contaminating compounds in LBE.
It involves the implementation of the `LBEContaminationTester` class, with:

- [x] the test_init_fromX method in `test_lbe_fromX_spanT`.
- [x] the `test_min` method in `test_lbh15_bounds.py`.
- [x] the `test_max` method in `test_lbh15_bounds.py`.
- [x] the `test_T_at_min` method in `test_lbh15_bounds.py`.
- [x] the `test_T_at_max` method in `test_lbh15_bounds.py`.

This issue is handled as one of the tasks of issue #188.

**Comment by lelaus** [comment]
The first task of this issue has been managed. Since constant properties are added, the method `is_constant()` has been added to the class `PropertyInterface` by merging branch _189_contamination_tests_.

No need to change the doc.
Tests for LBE contaminant properties have been added.
