### ISSUE TITLE
Define module for messages, errors and warnings

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#2]
Define a specific module for messages, errors and warnings I/O:
- predefined strings
- templeate strings with replaceable arguments wrapped by proper function

**Comment by ndarmage** [comment]
I recommend the py package `logging` to handle any kind of message during program execution.

Use of predefined python exception classes is recommended. I do not see at the moment the need of new or custom exception classes, though there might be in the future.

**Comment by ndarmage** [comment]
This issue is about customisation and standardisation of messages addressed to the user during the program execution. It is deferred to future versions since the current use of standard Exception classes seems satisfactory, limiting also the number of total code lines.
