### ISSUE TITLE
Generation of the documentation - issue with datetime format

### ISSUE THREAD

**Issue by mragey** [newcleo-dev-team/lbh15#206]
Hello,

The generation of the documentation is not possible due to the date formatting in conf.py file:
File "XXX\AppData\Roaming\Python\Python310\site-packages\sphinx\config.py", line 509, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "XXX\Documents\sandbox\lbh15\docs\conf.py", line 200, in <module>
    str(datetime.strptime(date_list[1], '%B').month) + "/" + date_list[2]
  File "C:\Program Files\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'April' does not match format '%B

Configuration of the environment:
OS : Windows
Python : 3.10
DateTime : 5.5
sphinx 7.3.7

**Comment by lelaus** [comment]
The signaled bug has been reproduced on Windows 11 OS.
It seems related to the locale settings.
A fixing has been identified and implemented in a8f79d7 by imposing the locale to use in `conf.py`.
@mragey , could you please check whether the implemented solution fixes also the bug you found?

**Comment by mragey** [comment]
It fixes the issue and the documentation can be now be generated on Windows 11.

**Comment by panDanieleN** [comment]
Merged into master. 

Update doc generation as explained in the issue thread. 

No need to update tests
