### ISSUE TITLE
Define iron solubility property classes for Bismuth

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#25]
Define a specific module in `properties` sub-package containing iron solubility correlation for liquid bismuth.

**Comment by panDanieleN** [comment]
Modify `test_lbh15_bounds.py` to check the bounds of the iron solubility correlations.

**Comment by klucie** [comment]
Define both the module bismuth_thermochemical_properties and modifiy the test test_lbh15_bounds.

branch : fe_sol_bismuth
commit : 75b9a2d8c2bbf3645c7f15901e3a70dbf14e17c8

**Comment by panDanieleN** [comment]
Merged into master. 

Documentation update addressed in #38
