### ISSUE TITLE
Define solubility of elements in Bismuth

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#27]
Define the elements' solubility in bismuth as done for the iron (see issue #25)

**Comment by klucie** [comment]
Define Cr and Ni solubility in bimuth_thermochemical_properties and update of properties_bounds.json to perform test_lbh15_bounds.py

branch: bi_sol
commit: 9750ee73480cad67682346165bbebb5f85ca9ebd

**Comment by klucie** [comment]
Adding all the correlations related to solubility in bismuth in solubility_in_bismuth.py 

branch: bi_sol
commit: 1949cb3a8160402d509d8aacbe08f18f0a93f6e3

**Comment by panDanieleN** [comment]
Merged into master. 

Documentation update addressed in #38
