### ISSUE TITLE
Properties module attribute of LiquidMetalInterface must be a dictionary to handle multiple modules

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#29]
In order to load properties from different modules, as proposed in issue #28, the `_properties_module` attribute of `LiquidMetalInterface` class (and its derived ones) must become a dictionary (as done for the `__custom_properties_path` attribute).

**Comment by panDanieleN** [comment]
When loading properties, a check must be done to verify that the class that is going to be instantiated is not abstract (see issue #23).

**Comment by klucie** [comment]
Modification of the __load_properties so it loads properties from different modules as proposed in the issue #28.
Modification of the __init__.py according those changes, proposed in issue #28.
Adding of new constants (oxygen, bismuth, lead and lbe molar masses) needed for the implementation of the new correlations. 

branch: modif_thermochemical
commit: 04f2f4624447c3a6ef8355c4a8bd6968cf25b0c6

**Comment by panDanieleN** [comment]
The attribute was eventually implemented as list of module names in #55.
