### ISSUE TITLE
Property objects shall provide information about correlation features (min, max, etc..) rather than LiquidMetal objects

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#3]
Currently static method like cp_min, T_at_cp_min are embedded in LiquidMetal (LM) object classes (Lead, Bismuth, LBE). Due to the dynamic methodology of properties addition in LM objects, this approach shall be avoided.
Example of undesired behaviour:
. user adds its own cp correlation for Lead
. user asks for minimum value of cp ->> lbh15 can provide only minimum of cp for "gurvich1991" and "sobolev2011" correlation

Implementation must be in some sense "static": user asks those information without instantiation of specific property or perhaps he needs them to take decision at instantiation phase of LM.
Example:
. user wants to instantiate Bismuth knowing its cp value ->> in order to select the first or second root of the function he probably needs to know which is the function minimum

**Comment by ndarmage** [comment]
I confirm the interest in the suggested improvement, which can motivate a post-release, with version 1.1.0.

**Comment by panDanieleN** [comment]
Defined compute_bounds method to compute property min. max, T_at_min and T_at_max in correlation validity range. If method is not invoked the default values are inf and -inf. 

The way to retrieve those bounds is not related to static methods since it seems easy to use it with an instance of property object. (NEED TO UPDATE DOCUMENTATION)

Defined regression test to compare property values with benchmark in json file.

**Comment by ndarmage** [comment]
I suggest using nan instead of inf as initial value for the codomain bounds of a property function. This will remind that the range in the  function codomain is not set yet.

**Comment by panDanieleN** [comment]
> I suggest using nan instead of inf as initial value for the codomain bounds of a property function. This will remind that the range in the function codomain is not set yet.

Done in commit 22d40ce8b28dae686076d6fd6f5279b7e3ab8f58
branch master

**Comment by panDanieleN** [comment]
Merged into master
