### ISSUE TITLE
Modify the test_lbh15_fromX so that it dynamically tests the initialization from all the available properties

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#31]
Replace all the specific test functions with just one that checks the initialization from all the available properties.
This shall be done for all the three liquid metals. 
The test shall be dynamic so that when new properties are available they are going to be automatically tested.

**Comment by klucie** [comment]
Modification of test_lbh15_fromX to have a dynamical test of the initialization for the available properties (lead_properties.py, lbe_properties.py, bismuth_properties.py).

branch: testfromX
commit: ffe15b2412f5519a93eef6c81cc6ae11b6b1c9be

**Comment by panDanieleN** [comment]
Merged into the master. No need to modfy the documentation.

**Comment by panDanieleN** [comment]
Fix `load_prop` function in `test_lbh15_fromX` since it is not loading correctly the properties on which execute the test.

**Comment by panDanieleN** [comment]
Merged into master.

Fixed test `test_lbh15_fromX.py`

No need to update the documentation.
