### ISSUE TITLE
Define module containing thermochemical properties in Bismuth

### ISSUE THREAD

**Issue by klucie** [newcleo-dev-team/lbh15#34]
Add the thermochemical correlations related to bismuth in the properties sub-package, according to the package structure defined in issue #28.

**Comment by klucie** [comment]
Define the module bismuth_thermochemical.py containing all the thermochemical correlations related to bismuth.

branch: bi_thermochemical
commit: 1bc744ea49075d7bd37820d3443d9138ce248839

**Comment by klucie** [comment]
Add of the __init__.py of the properties sub-package bismuth_thermochemical_properties, containing bismuth_thermochemical.py, solubility_in_bismuth.py and diffusivity_in_bismuth.py 

branch: bi_thermochemical
commit: f5e6cd1

**Comment by klucie** [comment]
Modification of the long_name form to correct a display error.

branch: modif_thermochemical
commit: 0e65eed

**Comment by panDanieleN** [comment]
Merged into master.

Documentation update addressed in #38
