### ISSUE TITLE
Define module containing solubility of elements in LBE

### ISSUE THREAD

**Issue by klucie** [newcleo-dev-team/lbh15#35]
Add the solubility correlations related to LBE in the properties sub-package, according to the package structure defined in issue #28.

**Comment by klucie** [comment]
Define the module solubility_in_lbe.py containing all the solubility correlations related to LBE and the __init__.py of the properties sub-package lbe_thermochemical_properties. 

branch: lbe_solubility
commit: 8b2c0c1ffa7664ae4619354271998998abd91c7a

**Comment by panDanieleN** [comment]
Merged into master.

Documentation update addressed in #38
