### ISSUE TITLE
Define module containing thermochemical correlations related to LBE

### ISSUE THREAD

**Issue by klucie** [newcleo-dev-team/lbh15#37]
Add the thermochemical correlations related to LBE in the properties sub-package, according to the package structure defined in issue #28.

**Comment by klucie** [comment]
Define the module thermochemical_in_lbe.py containing all the thermochemical correlations related to LBE in the properties sub-package lbe_thermochemical_properties.

branch: lbe_thermochemical
commit: a45bd74fde76135c0cece4f063160ddb176d0af8

**Comment by klucie** [comment]
Modification of the long_name form to correct a display error.

branch: modif_thermochemical
commit: 3b0b9fb

**Comment by panDanieleN** [comment]
Merged into master.

Documentation update addressed in #38
