### ISSUE TITLE
Define module containing oxygen limits correlations related to LBE

### ISSUE THREAD

**Issue by klucie** [newcleo-dev-team/lbh15#38]
Add the oxygen limits correlations related to LBE in the properties sub-package, according to the package structure defined in issue #28.

**Comment by klucie** [comment]
Define the module lbe_oxygen_limits.py containing all the oxygen limits correlations related to LBE in the properties sub-package lbe_thermochemical_properties.

branch: lbe_olim
commit: e853da8ab75f8bc8c4c33e577843d2e839b9a144

**Comment by panDanieleN** [comment]
Merged into master.

Documentation update addressed in #38
