### ISSUE TITLE
Check use of correlation acronyms

### ISSUE THREAD

**Issue by ndarmage** [newcleo-dev-team/lbh15#4]
Sometimes, correlations from the reference handbook miss the name used as acronym or identifier. In such case, the correlation name is `lbh15`. Please, check the handbook in case existing names for a correlation were neglected by mistake.

When the user adds his/her own correlation for a given property, this last becomes the default one also in case more correlations were already available. Check the documentation for correct information communicated to the user.

**Comment by panDanieleN** [comment]
Done Handbook review:
commit: f4faf3a0fdc1064223ad0b22aa7d1a8ce4d8e207
branch: master
