### ISSUE TITLE
Define module containing diffusivity of elements in Lead

### ISSUE THREAD

**Issue by klucie** [newcleo-dev-team/lbh15#40]
Add the diffusivity correlations related to lead in the properties sub-package, according to the package structure defined in issue #28.

**Comment by klucie** [comment]
Define the module diffusivity_in_lead.py containing all the diffusivity correlations related to lead in the properties sub-package lead_thermochemical_properties.

branch: pb_diffusivity
commit: 862e116f05b6033db4415d8d2e6dd79e23e8e872

**Comment by panDanieleN** [comment]
Merged into master.

Documentation update addressed in #48
