### ISSUE TITLE
Define module containing thermochemical correlations related to Lead

### ISSUE THREAD

**Issue by klucie** [newcleo-dev-team/lbh15#41]
Add the thermochemical correlations related to lead in the properties sub-package, according to the package structure defined in issue #28.

**Comment by klucie** [comment]
Define the module thermochemical_in_lead.py containing all the thermochemical correlations related to lead in the properties sub-package lead_thermochemical_properties.

branch: pb_thermochemical
commit: effbdcd1ddd5dcc28d1eb58de672dec37464d715

**Comment by klucie** [comment]
Modification of the long_name form to correct a display error.

branch: modif_thermochemical
commit: b361a27

**Comment by panDanieleN** [comment]
Merged into master.

Documentation update addressed in #48
