### ISSUE TITLE
Define module containing oxygen limits correlations related to Lead

### ISSUE THREAD

**Issue by klucie** [newcleo-dev-team/lbh15#42]
Add the oxygen limits correlations related to lead in the properties sub-package, according to the package structure defined in issue #28.

**Comment by klucie** [comment]
Define the module lead_oxygen_limits.py containing all the oxygen limits correlations related to lead in the properties sub-package lead_thermochemical_properties.

branch: pb_olim
commit: 0e9853a0856fe265c8207fdb7483528a67181f64

**Comment by klucie** [comment]
Modification of the long_name form to correct a display error.

branch: modif_thermochemical
commit: ddd92d9

**Comment by panDanieleN** [comment]
Merged into master.

Documentation update addressed in #48
