### ISSUE TITLE
Update the API guide of the documentation to include the new thermochemical properties

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#43]
Update the API guide structure according to modules defined in issue #28.

**Comment by klucie** [comment]
Update of the API guide with creation of .rst files for new properties, according to the structure defined in issue #28.
Modification of properties.rst description so it takes into account the new modules.

branch: modif_thermochemical
commit: 126ebf11263129dfa71c7a028cfbde2eb6231e4d
