### ISSUE TITLE
Update the documentation to show the new thermochemical properties

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#47]
Update the introduction and examples section of the documentation. 
Define a table where all the new properties are listed and updated the examples to show their usage.

**Comment by klucie** [comment]
Other minor modifications:
- add 2 basic example with the new correlations
- update the laste example
- update the prints in the "advanced usage" section
- fix the reference in the "advanced usage" section
- in API guide, add "lbh15." before "properties"
- in API guide, in lbh15.lead, lbh15.lbe, lbh15.bismuth modules, remove the "lbh15." in the title to be consitent, remove the cp correlation that is not the default one and add the default correlations of the new properties

**Comment by panDanieleN** [comment]
The density correlation formula in the documentation shall be updated to show the pressure dependence.

**Comment by panDanieleN** [comment]
Yet to do:
- update the prints in the "advanced usage" section -> change the output of `correlations_available` inserting thermochemical properties.
- "in API guide, in lbh15.lead, lbh15.lbe, lbh15.bismuth modules, remove the "lbh15." in the title to be consitent, remove the cp correlation that is not the default one and add the default correlations of the new thermochemical properties"

**Comment by panDanieleN** [comment]
Need to update the last example of the "Basic usage" to show the pressure value returned by the `__repr__` method as well.

**Comment by lelaus** [comment]
In 25892a7 the implementation of the correlations of the lower limits of oxygen concentration in lead have been modified in order to improve their computational efficiency

**Comment by lelaus** [comment]
In c74a439 the decorators are all put within the same module, in order to make their management simpler and to improve the readability of the code.

**Comment by panDanieleN** [comment]
Merged into master.

Update documentation described by the issue.

No need to update tests.
