### ISSUE TITLE
Type Hints and Type Checking

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#49]
- [1] implement type hints
- [2] apply the type checking to public methods by means of decorators

**Comment by panDanieleN** [comment]
Add type hints and type checking also into thermochemical properties' modules.

**Comment by lelaus** [comment]
To solve a bug related to the type check decorator: to enable it to deal with arguments represented by containers made by only one element.

**Comment by panDanieleN** [comment]
Merged into master.

No need for documentation and tests update.

**Comment by panDanieleN** [comment]
Fix the type hint decorator since it doesn't allow the initialization from property.

**Comment by panDanieleN** [comment]
Merged into master.

No need for documentation and tests update.
