### ISSUE TITLE
Set correlation functionality shall impact only instances rather then class itself

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#5]
In current release, setting correlations to use determines the following undesired behavour: 

    >>> from lbh15 import Lead
    >>> Lead.set_correlation_to_use('cp', 'sobolev2011')
    >>> ll = Lead(T=668.15)
    >>> ll.cp
    146.7859768569852
    >>> Lead.set_correlation_to_use('cp', 'gurvich1991')
    >>> ll.cp
    146.7859768569852
    >>> ll2 = Lead(T=668.15)
    >>> ll2.cp
    146.77472503511203
    >>> ll.cp
    146.77472503511203

In practice, when a new instance is created, the new corralation impacts also the previously created one, thus changing its cp value. This is because property addition is a class related functionality and it is currently hanlded un __new__ dunder method.

The following points shall be guaranteed:
- previous instances' properties must not change because of new correlation choice selected via class method.
- set correlation determines the correlation to use in instances initialized after it has been invoked.
- instances might have the possibility to change the correlation to use.

**Comment by panDanieleN** [comment]
solved in
commit: 43dd02ea16ac041c0f9a969b89f70f80f8c2720d
branch: instanceAttributes

**Comment by ndarmage** [comment]
Please post the new behavior of the code shown above, which originated the current issue.

**Comment by panDanieleN** [comment]
>>> from lbh15 import Lead
>>> Lead.set_correlation_to_use('cp', 'sobolev2011')
>>> ll = Lead(T=668.15)
>>> ll.cp
146.7859768569852
>>> Lead.set_correlation_to_use('cp', 'gurvich1991')
>>> ll2 = Lead(T=668.15)
>>> ll2.cp
146.77472503511203
>>> ll.cp
146.7859768569852

**Comment by panDanieleN** [comment]
Merged into master
