### ISSUE TITLE
Attribute Change within "_lbh15.py"

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#55]
rename `_properties_module` as `_properties_modules_list` and convert its type from string to list of string; there are no attribute matching names between `LiquidMetalInterface` and liquid metal specific classes

**Comment by panDanieleN** [comment]
This fixes what has been done in issue #29 .

**Comment by lelaus** [comment]
Name inconsistencies between LiquidMetalInterface and derived classes have been solved.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
