### ISSUE TITLE
"_properties" Dict ("_lbh15.py") Keys Modification

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#56]
- [1] keys are strings currently made by two components separated by the underscore "_"; the first component is the actual name of the property, the second component is the name of the liquid metal the property is related to; the second component is useless since the `_properties` dict is instance-related, thus remove it;
- [2] as a consequence, delete the `__generate_key()` method and all its occurrences;
- [3] as a consequence, the `__load_properties()` method becomes useless; delete the `__load_properties()` method and rename the `__property_list()` method as `__load_properties();`

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
