### ISSUE TITLE
"__property_list()" Method ("_lbh15.py") Improvement

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#57]
- [1] the description is missing;
- [2] remove the `if len(eff_modules) > 0` since useless;
- [3] wrap the conditions `inspect.isclass(obj) and obj is not PropertyInterface and not inspect.isabstract(obj) and issubclass(obj, PropertyInterface)` " into a predicate to pass as second argument to the `inspect.getmembers();` this way the returned modules are already filtered;
- [4] reorganize the for loop:
- [4.A] make a for loop for collecting into the `mod` list the pairs retrieved from all the modules to load; the elements of `mod` are represented by the (object name, object) pairs;
- [4.B] extract from `mod` the list of all the objects, and convert it into the corresponding set, thus removing the duplicates;
- [4.C] make a for loop over all the elements within the set, thus instantiating the corresponding object and putting it within the list to return directly; this way instances are created only when they are required, and the list to return should not be retrieved within each for iteration;

**Comment by lelaus** [comment]
Watch out: after solving the issue #56 , the current issue is not related to the "__property_list()" method, but to the method named "__load_properties()".

**Comment by lelaus** [comment]
Task 1 already managed in issue #56 .

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
