### ISSUE TITLE
"__load_custom_properties()" Method ("_lbh15.py") Improvement

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#59]
remove the `customproperty_obj_list` object, since the `cls.__property_list(modules)` object can be returned directly;

**Comment by lelaus** [comment]
Following the modifications applied when solving issue #58 , the current issue does not imply any action, since the `customproperty_obj_list` cannot be deleted anymore.

**Comment by panDanieleN** [comment]
Closed since no actions to do.
