### ISSUE TITLE
Attribute Storing the Available Correlations ("_lbh15.py")

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#61]
- [1] create an instance attribute named `__instance_available_corrs`: it should be a dict having the property names as keys and the list of the correspondingly available correlation names as value;
- [2] this dict could be filled by a dedicated private method, which implements the second part of the already implemented `correlations_available()` public method;
- [3] the private method is then called even within the `correlations_available()` public method;

**Comment by lelaus** [comment]
Correspondingly to the tasks listed in the previous comment, the following actions have been taken:

- [1] the attribute storing all the available correlations have been named "_available_correlations_dict";
- [2] this attribute is filled by calling the `__extract_available_correlations` private static method implemented when issue #60 has been solved; this action is performed when the instance is built, more precisely within the `__fill_instance_properties` method;
- [3] this task has been already handled when issue #60 has been solved.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
