### ISSUE TITLE
"__fill_instance_properties()" Method ("_lbh15.py") Improvement

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#62]
- [1] remove the `add_property` boolean flag; collect all the boolean conditions into one single condition the `__add_property()` method call depends on; this way the reading should become simpler;
- [2] put the key deleting operations within the `__check_properties()` method since they are related to the management of the `__corr2use` attribute as the entire method `__check_properties()` itself; for readability reasons, the key deleting operations could be encapsulated within a private method named `delete_corrs()`;
- [3] remove the `if key_to_remove in self._correlations_to_use` statement since useless;

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
