### ISSUE TITLE
"__add_property()" Method ("_lbh15.py") Improvement

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#63]
- [1] remove the `key` variable as the `property_object.name` is already the `__properties` key;
- [2] delete the `new_property_info` function, and pass as third argument to the `setattr()` method directly the `info()` function of the property, thus simplifying the implementation;

**Comment by lelaus** [comment]
The first task does not require any intervention because deleting the `key` variable implies an increased computational load.

**Comment by lelaus** [comment]
The function passed to `setattr()` method is built differently.
So far it was encapsulated within a function declared with `def`, and then passed to the `setattr()` method. Now it is passed directly to the `setattr()` method by means of a `lambda` function.
Pay attention: PEP8 discourages the use of `lambda` functions, but only when they are used in assignment expressions, thus binding the `lambda` function to an identifier [](https://peps.python.org/pep-0008/). In the present case, the `lambda`  function is not assigned to any identifier, thus passing all the checks provided by `pylint` and `pycodestyle`.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
