### ISSUE TITLE
"__fill_class_attributes" Method ("_lbh15.py") Improvement

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#65]
- [1] move the check on the length of the arguments to the constructor, thus identifying any error before doing any operation; correspondingly, this method should receive two input arguments, the name of the property and its value;
- [2] for retrieving `valid_prop` do not use `properties_for_initialization()` method, but retrieve the names of the properties stored within the `instance_loaded_prop_obj_list` instance variable #61, and add the temperature name to them;
- [3] substitute the for loop on the list of the names of the valid properties with the `list_to_print += '\n'.join(valid_prop)` instruction; this way the code is more compact;
- [4] move the `self._set_constants()` call to the constructor, thus separating the targets;
- [5] rename the method as `__fill_instance_attributes()` as more aligned with what the method does;

**Comment by lelaus** [comment]
The task #2 has already been fulfilled in #64.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
