### ISSUE TITLE
"__assign_p()" Method ("_lbh15.py") Improvement

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#68]
encapsulate the value check into a dedicated private method, in accordance with what is done within the `__assing_T()` method

**Comment by lelaus** [comment]
The readability improvement of `__assign_p()` method has been done by refactoring the if statement within, and not by encapsulating the check within another method, since the check is extremely simple. The same refactoring of the if statement has been applied to the `__assign_T()` method.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
