### ISSUE TITLE
"change_correlation_to_use()" Method ("_lbh15.py") Improvement

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#69]
- [1] remove the `key` variable and substitute it with the `property_name` #56;
- [2] avoid calling the `__fill_instance_properties()` method; call the lighter `__add_property()` method;
- [3] add the `else` branch where warning the user that the specified property is not among the currently set ones;

**Comment by lelaus** [comment]
Task 1 already fulfilled when issue #56 has been solved.

**Comment by lelaus** [comment]
3 if statements added for covering all possible cases where nothing should be done.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
