### ISSUE TITLE
Constants Into Commons

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#71]
- [1] add the _lbh15_ default correlation name;
- [2] delete the `GURVICH_KEYWORD` and the `SOBOLEV_KEYWORD` constants, since there is currently no reason why they should be there;

**Comment by lelaus** [comment]
Task 1 not fulfilled for the same reason behind the task 2.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation and tests.
