### ISSUE TITLE
lbh15 Within IAEA Oncore Codes List

### ISSUE THREAD

**Issue by lelaus** [newcleo-dev-team/lbh15#73]
Add into the readme the info about the inclusion of the "lbh15" code within the Open-source Nuclear Codes for Reactor Analysis list.

**Comment by panDanieleN** [comment]
Added link to oncore site by IAEA in _Introduction_ section of the readme.

Branch: 73_iaea_oncore
Commit: 5a357e96f19721ba21266f9d92e3807fb17550f6

**Comment by lelaus** [comment]
Merged into master.

No need to update tests.

Modified documentation as required by the issue itself.
