### ISSUE TITLE
Update test_custom_properties to test correct assignment of custom properties to different liquid metal classes

### ISSUE THREAD

**Issue by panDanieleN** [newcleo-dev-team/lbh15#86]
Modify the test as follows:

- define `lbe_properties.py` and `bismuth_properties.py` implementing a custom density property for `LBE` and `Bismuth` classes (rename `properties.py` into `lead_properties.py` as well).
- In `test_custom_properties.py` use the method `set_custom_properties_path` with all the three liquid metal classes.
- Define 3 strings that contain the expected output of `rho_info()` method, one per each liquid metal class.
- Define 3 tests in which the outcome of `rho_info()` of  the liquid metal instance with the custom property assigned is compared with the strings defined at the previous point,

**Comment by lelaus** [comment]
All the tasks of the issue have been covered.

**Comment by panDanieleN** [comment]
Merged into master.

No need to update documentation.
